# Generated by Django 4.0.4 on 2022-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('AA', 'Aguardando aprovação'), ('C', 'Em criação'), ('F', 'Finalizado')], default='AA', max_length=2),
        ),
    ]
