# Generated by Django 4.0.4 on 2022-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('AA', 'Aguardando aprovação'), ('C', 'Em criação'), ('F', 'Finalizado')], default='C', max_length=2),
        ),
    ]
